[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

monitor_speed = 115200
upload_speed = 115200

board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.partitions = huge_app.csv

lib_deps =
    sandeepmistry/LoRa@^0.8.0
    arduino-libraries/Arduino_JSON@^0.2.0
    alvarowolfx/ESP32QRCodeReader@^1.1.0
    marcoschwartz/LiquidCrystal_I2C@^1.1.4

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -Wno-deprecated-declarations
    -Wno-implicit-function-declaration